sensi_yaml_gui_edit:
    pattern: /edit/{config_file}
    defaults: { _controller: SensiYamlGuiBundle:Default:edit }
    requirements:
        config_file: .+

sensi_yaml_gui_list:
    pattern: /list
    defaults: { _controller: SensiYamlGuiBundle:Default:list }
